### ISSUE TITLE
Test failed in cn.net.polyglot.verticle.WebServerTest

### ISSUE THREAD

**Issue by minosniu** [whitewoodcity/social-vertex#4]
Results :

Tests in error: 
  testTemplate(cn.net.polyglot.verticle.WebServerTest)

Tests run: 17, Failures: 0, Errors: 1, Skipped: 0

> SEVERE: Unhandled exception
> java.lang.NullPointerException
> 	at cn.net.polyglot.verticle.WebServerTest$testTemplate$1.handle(WebServerTest.kt:65)
> 	at cn.net.polyglot.verticle.WebServerTest$testTemplate$1.handle(WebServerTest.kt:23)
> 	at io.vertx.ext.web.client.impl.HttpContext.handleFailure(HttpContext.java:282)
> 	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:276)
> 	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:251)
> 	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
> 	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
> 	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:248)
> 	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:258)
> 	at io.vertx.ext.web.client.impl.HttpContext.fail(HttpContext.java:238)
> 	at io.vertx.ext.web.client.impl.HttpContext.lambda$handleSendRequest$9(HttpContext.java:396)
> 	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
> 	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:139)
> 	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleException(Http1xClientConnection.java:515)
> 	at io.vertx.core.http.impl.Http1xClientConnection.handleClosed(Http1xClientConnection.java:882)
> 	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$5(VertxHandler.java:164)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
> 	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
> 	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
> 	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
> 	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:164)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
> 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
> 	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:282)
> 	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by zxj5470** [comment]
Never mind, we haven't finished it yet. Just waiting for it. 
Now we comment this test temporarily.

**Comment by minosniu** [comment]
Solved with the latest commit.
